### ISSUE TITLE
cookies and followAllRedirects

### ISSUE THREAD

**Issue by Waltari10** [marcodave/protractor-http-client#6]
Is there anyway to enable jar? Kinda like in node Request you can just set 

`const request = require('request').defaults({ jar: true });`

Also how do I enable post and put requests to followAllRedirects?

  `  followAllRedirects: true,`

**Comment by marcodave** [comment]
Hi! for setting common options for the `request` module, such as the cookie jar, you can use
```
HttpClient.commonRequestOptions({ jar: true });
```

as for the `followAllRedirects: true`, I would suggest you to use the `request(options)` method in the `HttpClient`, where you can pass any options accepted by the request module, e.g.
```
httpClient.request({
  url: "my-url",
  followAllRedirects: true,
  method: "POST",
  body: "....."
})
```
